services:
  web-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.simplified
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    volumes:
      - ./web/build:/app/web/build:ro