global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'web-analyzer'
    static_configs:
      - targets: ['web-analyzer:8080']  # Use the service name directly
    metrics_path: /metrics