openapi: 3.0.0
info:
  title: Web Page Analyzer API
  description: API for analyzing web pages, extracting HTML version, title, headings, links, and detecting login forms.
  version: 1.0.0
  contact:
    name: Web Analyzer Team

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/analyze:
    post:
      summary: Analyze a web page
      description: Fetches and analyzes a web page by URL, returning information about its structure and content.
      operationId: analyzeWebPage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisRequest'
      responses:
        '200':
          description: Successful analysis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '400':
          description: Bad request (invalid URL format)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Failed to fetch or analyze the URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /api/health:
    get:
      summary: Health check
      description: Returns the health status of the API
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

components:
  schemas:
    AnalysisRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          description: URL of the web page to analyze
          example: https://example.com
    
    AnalysisResponse:
      type: object
      properties:
        htmlVersion:
          type: string
          description: Detected HTML version
          example: HTML5
        title:
          type: string
          description: Page title
          example: Example Domain
        headings:
          $ref: '#/components/schemas/HeadingCount'
        links:
          $ref: '#/components/schemas/LinkAnalysis'
        containsLoginForm:
          type: boolean
          description: Whether the page contains a login form
          example: false
    
    HeadingCount:
      type: object
      properties:
        h1:
          type: integer
          description: Number of h1 headings
          example: 1
        h2:
          type: integer
          description: Number of h2 headings
          example: 2
        h3:
          type: integer
          description: Number of h3 headings
          example: 3
        h4:
          type: integer
          description: Number of h4 headings
          example: 0
        h5:
          type: integer
          description: Number of h5 headings
          example: 0
        h6:
          type: integer
          description: Number of h6 headings
          example: 0
    
    LinkAnalysis:
      type: object
      properties:
        internal:
          type: integer
          description: Number of internal links
          example: 5
        external:
          type: integer
          description: Number of external links
          example: 3
        inaccessible:
          type: integer
          description: Number of inaccessible links
          example: 1
    
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          description: HTTP status code
          example: 502
        message:
          type: string
          description: Error message
          example: Failed to analyze URL: HTTP error 404 Not Found