basePath: /
definitions:
  models.AnalysisRequest:
    properties:
      url:
        example: https://example.com
        type: string
    type: object
  models.AnalysisResponse:
    properties:
      containsLoginForm:
        example: false
        type: boolean
      headings:
        $ref: '#/definitions/models.HeadingCount'
      htmlVersion:
        example: HTML5
        type: string
      links:
        $ref: '#/definitions/models.LinkAnalysis'
      title:
        example: Example Domain
        type: string
    type: object
  models.ErrorResponse:
    properties:
      message:
        example: 'Failed to analyze URL: HTTP error 404 Not Found'
        type: string
      statusCode:
        example: 502
        type: integer
    type: object
  models.HeadingCount:
    properties:
      h1:
        example: 1
        type: integer
      h2:
        example: 2
        type: integer
      h3:
        example: 3
        type: integer
      h4:
        example: 0
        type: integer
      h5:
        example: 0
        type: integer
      h6:
        example: 0
        type: integer
    type: object
  models.LinkAnalysis:
    properties:
      external:
        example: 3
        type: integer
      inaccessible:
        example: 1
        type: integer
      internal:
        example: 5
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    name: Web Analyzer Team
  description: API for analyzing web pages, extracting HTML version, title, headings,
    links, and detecting login forms.
  title: Web Page Analyzer API
  version: "1.0"
paths:
  /api/analyze:
    post:
      consumes:
      - application/json
      description: Fetches and analyzes a web page by URL, returning information about
        its structure and content
      parameters:
      - description: URL to analyze
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AnalysisRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful analysis
          schema:
            $ref: '#/definitions/models.AnalysisResponse'
        "400":
          description: Bad request (invalid URL format)
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "502":
          description: Failed to fetch or analyze the URL
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Analyze a web page
      tags:
      - analysis
  /api/health:
    get:
      description: Returns the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
schemes:
- http
swagger: "2.0"
